#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

/* Layer reference:
 *   00 = Grephati-BZ (main AKL layout)
 *   01 = Qwerty (backup layout - mostly for gaming)
 *   02 = Other AKL layout (for testing out other layouts) - Currently not configured
 *   03 = Navigation and symbol layer
 */
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
                 KC_TAB, KC_Z, KC_L, KC_D, KC_W, KC_B, KC_J, KC_F, KC_O, KC_U, KC_SCLN, KC_BSLS,
                 TG(3), KC_N, KC_R, KC_T, KC_S, KC_G, KC_Y, KC_H, KC_E, KC_I, KC_A, KC_QUOT,
                 KC_LSFT, KC_Q, KC_X, KC_M, KC_C, KC_V, _______, _______, KC_K, KC_P, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
                 KC_LALT, KC_LCTL, MO(3), LT(3, KC_SPC), KC_RCTL, KC_RALT),
    [1] = LAYOUT(QK_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
                 KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSLS,
                 KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
                 KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, _______, _______, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
                 KC_LALT, KC_LCTL, KC_SPC, LT(3, KC_SPC), KC_RCTL, KC_RALT),
    [2] = LAYOUT(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
                 RM_TOGG, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, QK_BOOT,
                 RM_NEXT, KC_MPRV, KC_MNXT, KC_VOLU, KC_PGUP, KC_UNDS, KC_EQL, KC_HOME, RM_HUEU, RM_SATU, RM_VALU, KC_BSLS,
                 KC_MUTE, KC_MSTP, KC_MPLY, KC_VOLD, KC_PGDN, KC_MINS, KC_LPRN, _______, KC_PLUS, KC_END, RM_HUED, RM_SATD, RM_VALD, EE_CLR,
                 _______, _______, _______, _______, _______, _______),
    [3] = LAYOUT(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11,
                 KC_GRV, KC_L, KC_LBRC, KC_RBRC, _______, KC_CAPS, KC_EQL, KC_PPLS, KC_MINUS, KC_UNDS, KC_HOME, KC_END,
                 TG(3), KC_LGUI, KC_LPRN, KC_RPRN, KC_ENT, _______, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_PGUP, KC_PGDN,
                 KC_LSFT, _______, KC_LCBR, KC_RCBR, TG(1), TG(2), _______, _______, KC_INS, KC_DEL, _______, _______, KC_PSCR, KC_RSFT,
                 KC_LALT, KC_LCTL, _______, KC_SPC, KC_RCTL, KC_RALT)
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

